# See here [1] for available images and runners
# [1] https://cern.service-now.com/service-portal?id=kb_article&n=KB0003690
image: "gitlab-registry.cern.ch/ci-tools/ci-worker:cc7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - lint

before_script:
  - . ./env.sh

build:
  stage: build
  tags:
    - cvmfs
    - docker
  script:
    - .gitlab-ci/install_MELA.sh
    - .gitlab-ci/install_MelaAnalytics.sh
    - export MELA_ROOT_DIR=${HZZ2L2NU_BASE}/JHUGenMELA/MELA
    - export ROOT_INCLUDE_PATH=${ROOT_INCLUDE_PATH}:${MELA_ROOT_DIR}/interface
    - export MELA_ANALYTICS_ROOT_DIR=${HZZ2L2NU_BASE}/MelaAnalytics
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j $(nproc)

flake8:
  stage: lint
  tags:
    - cvmfs
    - docker
  script:
    - flake8
  allow_failure: true
