image: "gitlab-registry.cern.ch/ci-tools/ci-worker:slc6"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - lint

before_script:
  - . ./env.sh

build:
  stage: build
  tags:
    - cvmfs
    - docker
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make

flake8:
  stage: lint
  tags:
    - cvmfs
    - docker
  script:
    - flake8
  allow_failure: true
