period: "2016"
luminosity: 35921.876  # "Golden" data from 07Aug2017 re-reconstruction

dataset_stems:
- dataset_settings.yaml

run_sampler:
  luminosity: Lumi/lumi.yaml
  range: [272007, 284044]

# The choice of dilepton triggers is based on [1-3].
# [1] https://indico.cern.ch/event/904978/#172-triggers-revisited
# [2] https://indico.cern.ch/event/904979/#178-triggers-revisited-episode
# [3] https://indico.cern.ch/event/944264/#176-trigger-studies
trigger_filter:
  ee:
  - triggers: [
      Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ, DoublePhoton60,
      Ele25_eta2p1_WPTight_Gsf, Ele27_WPTight_Gsf, Photon175
    ]
  - triggers: [DoubleEle33_CaloIdL_GsfTrkIdVL]
    run_range: [272007, 278822]
  - triggers: [DoubleEle33_CaloIdL_MW]
    run_range: [272007, 276437]
  - triggers: [DoubleEle33_CaloIdL_MW]
    run_range: [278873, 284044]
  - triggers: [Ele27_eta2p1_WPLoose_Gsf]
    run_range: [272007, 280385]
  mumu:
  - triggers: [
      Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ, Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ,
      IsoMu24, IsoTkMu24, Mu50
    ]
  - triggers: [Mu17_TrkIsoVVL_Mu8_TrkIsoVVL, Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL]
    run_range: [272007, 280385]
  - triggers: [TkMu50]
    run_range: [274954, 284044]
  emu:
  - triggers: [
      Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL,
      Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL
    ]
    run_range: [272007, 280385]
  - triggers: [Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ]
    run_range: [278273, 284044]
  - triggers: [Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ]
    run_range: [280919, 284044]
  - triggers: [
      Ele25_eta2p1_WPTight_Gsf, Ele27_WPTight_Gsf, Photon175
    ]
  - triggers: [Ele27_eta2p1_WPLoose_Gsf]
    run_range: [272007, 280385]
  - triggers: [
      IsoMu24, IsoTkMu24, Mu50
    ]
  photon:
  - triggers: [
      Photon50_R9Id90_HE10_IsoM,
      Photon75_R9Id90_HE10_IsoM,
      Photon90_R9Id90_HE10_IsoM,
      Photon120_R9Id90_HE10_IsoM,
      Photon165_R9Id90_HE10_IsoM,
      Photon175
    ]
  
trigger_efficiency:
  ee:
    path: TriggerSF/2016/ee.root
  mumu:
    path: TriggerSF/2016/mumu.root
  emu:
    path: TriggerSF/2016/emu.root

l1t_prefiring: true

pileup_weight:
  data_profile: /pnfs/iihe/cms/store/user/yunyangl/ULsamples/zgamma/2023-05-21_2016noHIPM-NanoAODv9/pileup/pileup_profiles_data.root
  sim_profiles: /pnfs/iihe/cms/store/user/yunyangl/ULsamples/zgamma/2023-05-21_2016noHIPM-NanoAODv9/pileup/pileup_profiles_sim.root

met_filters:
  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2?rev=158#2016_data_and_MC_UL
  data:
  - "Flag_goodVertices"
  - "Flag_globalSuperTightHalo2016Filter"
  - "Flag_HBHENoiseFilter"
  - "Flag_HBHENoiseIsoFilter"
  - "Flag_EcalDeadCellTriggerPrimitiveFilter"
  - "Flag_BadPFMuonFilter"
  - "Flag_BadPFMuonDzFilter"
  - "Flag_eeBadScFilter"
  sim:
  - "Flag_goodVertices"
  - "Flag_globalSuperTightHalo2016Filter"
  - "Flag_HBHENoiseFilter"
  - "Flag_HBHENoiseIsoFilter"
  - "Flag_EcalDeadCellTriggerPrimitiveFilter"
  - "Flag_BadPFMuonFilter"
  - "Flag_BadPFMuonDzFilter"
  - "Flag_eeBadScFilter"

selection_cuts:
  z_mass_window: 15.0
  min_pt_ll: 55.0
  min_dphi_ll_ptmiss: 1.0
  min_dphi_jets_ptmiss: 0.25
  min_dphi_leptonsjets_ptmiss: 2.5

jets:
  # Use TightLepVeto working point for jet ID as recommended in https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016?rev=14
  jet_id_bit: 2
  min_pt: 30
  max_abs_eta: 4.7
  corrections:
    # https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC
    sim:
      - levels:
        - JERC/Summer19UL16_V7_MC_L1FastJet_AK4PFchs.txt
        - JERC/Summer19UL16_V7_MC_L2Relative_AK4PFchs.txt
        - JERC/Summer19UL16_V7_MC_L3Absolute_AK4PFchs.txt
        - JERC/Summer19UL16_V7_MC_L2L3Residual_AK4PFchs.txt
    data:
    - run_range: [272007, 276811]  # 2016BCD
      levels:
      - JERC/Summer19UL16APV_RunBCD_V7_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunBCD_V7_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunBCD_V7_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunBCD_V7_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [276831, 278768]  # 2016EF1
      levels:
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [278769, 278769]  # 2016F2GH
      levels:
      - JERC/Summer19UL16_RunFGH_V7_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer19UL16_RunFGH_V7_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer19UL16_RunFGH_V7_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer19UL16_RunFGH_V7_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [278770, 278800]  # 2016EF1
      levels:
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer19UL16APV_RunEF_V7_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [278801, 284044]  # 2016F2GH
      levels:
      - JERC/Summer19UL16_RunFGH_V7_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer19UL16_RunFGH_V7_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer19UL16_RunFGH_V7_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer19UL16_RunFGH_V7_DATA_L2L3Residual_AK4PFchs.txt
    uncertainty: JERC/Summer19UL16_V7_MC_Uncertainty_AK4PFchs.txt
  resolution:
    # Taken from https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution?rev=108
    sim_resolution: JERC/Summer20UL16_JRV3_MC_PtResolution_AK4PFchs.txt
    scale_factors: JERC/Summer20UL16_JRV3_MC_SF_AK4PFchs.txt

ptmiss:
  jer: true
  pog_jets: true
  XY_corrections: 2016
  is_ul: true

b_tagger:
  # Tag threshold and SF are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation106XUL16postVFP?rev=8#Supported_Algorithms_and_Operati
  branch_name: Jet_btagDeepFlavB
  tag_threshold: 0.0480
  tag_threshold_loose: 0.0480
  tag_threshold_medium: 0.2489
  tag_threshold_tight: 0.6377
  min_pt: 20
  max_abs_eta: 2.5

b_tag_weight:
  scale_factors: BTag/wp_deepJet_106XUL16postVFP_v3_preULformat_csvCommaWorkaround.csv
  efficiency: BTag/BTagEff_2016postVFP.root
  bottom_hist_name: bottom_eff
  charm_hist_name: charm_eff
  light_hist_name: light_eff


lepton_efficiency:
  muon:
    nominal:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_Nominal_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_Nominal_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    stat_up:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_StatUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_StatUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    stat_down:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_StatDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_StatDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    syst_up:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_SystUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_SystUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    syst_down:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_SystDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_SystDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    pileup_up:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_PUUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_PUUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    pileup_down:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_PUDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_PUDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    altMC_up:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_AltMCUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_AltMCUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
    altMC_down:
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_AltMCDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Muon_efficiencies_id_iso_2016.root:SF_AltMCDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
  electron:
    nominal:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_Nominal_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_Nominal_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    stat_up:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_StatUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_StatUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    stat_down:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_StatDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_StatDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    syst_up:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_SystUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_SystUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    syst_down:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_SystDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_SystDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    pileup_up:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_PUUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_PUUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    pileup_down:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_PUDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_PUDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    altMC_up:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_AltMCUp_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_AltMCUp_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true
    altMC_down:
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_AltMCDn_passId
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_id_iso_2016.root:SF_AltMCDn_passId_passIso
        schema: [eta, pt]
        clip_pt: true
      - path: LeptonSF/2016/Electron_efficiencies_tracking_2016.root:EGamma_SF2D
        schema: [eta, pt]
        clip_pt: true

photon_efficiency:
  photon:
  - PhotonSF/2016_Photon_SF_ID.root:EGamma_SF2D

photon_triggers:
  triggers:
    - name: HLT_Photon22_R9Id90_HE10_IsoM
      threshold: 24.2
      #Take 10% more, so that we are on the plateau (the pT in the name is the one at the middle of the turn-on curve, so at 50% efficiency).
    - name: HLT_Photon30_R9Id90_HE10_IsoM
      threshold: 33.
    - name: HLT_Photon36_R9Id90_HE10_IsoM
      threshold: 39.3
    - name: HLT_Photon50_R9Id90_HE10_IsoM
      threshold: 55.
    - name: HLT_Photon75_R9Id90_HE10_IsoM
      threshold: 82.5
    - name: HLT_Photon90_R9Id90_HE10_IsoM
      threshold: 99.
    - name: HLT_Photon120_R9Id90_HE10_IsoM
      threshold: 132.
    - name: HLT_Photon165_R9Id90_HE10_IsoM
      threshold: 181.5

  photon_prescale_map: Prescales/photon_prescales_2016.yaml

photon_reweighting:
  apply_nvtx_reweighting: false
  apply_eta_reweighting: false
  apply_pt_reweighting: false
  apply_mass_lineshape: false
  apply_mean_weights: false
  nvtx_reweighting: InstrMetReweighting/weight_nvtx_2016.root
  eta_reweighting: InstrMetReweighting/weight_eta_2016.root
  pt_reweighting: InstrMetReweighting/weight_pt_2016.root
  mass_lineshape: InstrMetReweighting/lineshape_mass_2016.root
  mean_weights: InstrMetReweighting/meanWeights_2016.root

# photon_filter:
  # file_location: /storage_mnt/storage/user/sicheng/share/data/PhotonFilter/2016

vbf_discriminant:
  meps:
  # AJetsVBFProbabilities_SpinZero_JHUGen (P_sig)
  - "Name:JJVBF_SIG_ghv1_1_JHUGen Alias:<Name> Process:HSMHiggs Production:JJVBF MatrixElement:JHUGen Cluster:J2JECNominal DefaultME:-1 Options:AddPConst=1"
  - "Name:JJVBF_SIG_ghv2_1_JHUGen Alias:<Name> Process:H0hplus Production:JJVBF MatrixElement:JHUGen Cluster:J2JECNominal DefaultME:-1"
  - "Name:JJVBF_SIG_ghv4_1_JHUGen Alias:<Name> Process:H0minus Production:JJVBF MatrixElement:JHUGen Cluster:J2JECNominal DefaultME:-1"
  - "Name:JJVBF_SIG_ghv1prime2_1E4_JHUGen Alias:<Name> Process:SelfDefine_spin0 Production:JJVBF MatrixElement:JHUGen Cluster:J2JECNominal Couplings:ghz1_prime2=10000,0 DefaultME:-1"
  # AJetsQCDProbabilities_SpinZero_JHUGen (P_alt)
  - "Name:JJQCD_SIG_ghg2_1_JHUGen Alias:<Name> Process:HSMHiggs Production:JJQCD MatrixElement:JHUGen Cluster:J2JECNominal DefaultME:-1 Options:AddPConst=1"
  mep_flags:
    p_sig_a1: JJVBF_SIG_ghv1_1_JHUGen
    p_sig_a2: JJVBF_SIG_ghv2_1_JHUGen
    p_sig_a3: JJVBF_SIG_ghv4_1_JHUGen
    p_sig_l1: JJVBF_SIG_ghv1prime2_1E4_JHUGen
    p_alt: JJQCD_SIG_ghg2_1_JHUGen
