period: "2016"
luminosity: 35921.876  # "Golden" data from 07Aug2017 re-reconstruction

dataset_stems:
- samples_2016.yaml

pileup_weight:
  data_profile: /pnfs/iihe/cms/store/group/HZZ2l2nu/Bonzais/Catalogs/September2018_newIDIso_v2/pileup_2016_certified.root
  default_sim_profile: /pnfs/iihe/cms/store/group/HZZ2l2nu/Bonzais/Catalogs/September2018_newIDIso_v2/pileup_RunIISummer16.root

jets:
  min_pt: 30
  max_abs_eta: 4.7
  corrections:
    sim:
    - levels:
      - JERC/Summer16_07Aug2017_V11_MC_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017_V11_MC_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017_V11_MC_L3Absolute_AK4PFchs.txt
    data:
    - run_range: [272007, 276811]  # 2016BCD
      levels:
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [276831, 278801]  # 2016EF1
      levels:
      - JERC/Summer16_07Aug2017EF_V11_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017EF_V11_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017EF_V11_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer16_07Aug2017EF_V11_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [278802, 284044]  # 2016F2GH
      levels:
      - JERC/Summer16_07Aug2017GH_V11_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017GH_V11_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017GH_V11_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer16_07Aug2017GH_V11_DATA_L2L3Residual_AK4PFchs.txt
    uncertainty: JERC/Summer16_07Aug2017_V11_MC_Uncertainty_AK4PFchs.txt
  resolution:
    sim_resolution: JERC/Summer16_25nsV1_MC_PtResolution_AK4PFchs.txt
    scale_factors: JERC/Summer16_25nsV1_MC_SF_AK4PFchs.txt

b_tagger:
  branch_name: Jet_btagCSVV2
  tag_threshold: 0.5426
  # Thresholds below are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation80XReReco?rev=14#AK4_jets
  min_pt: 20
  max_abs_eta: 2.4

b_tag_weight:
  scale_factors: efficiencyTables/CSVv2_Moriond17_B_H.csv
  efficiency_tables: efficiencyTables/btag-{flavors}.txt

lepton_efficiency:
  muon: 
  - LeptonSF/2016Muon_SF_ID.root:NUM_TightID_DEN_genTracks_eta_pt
  - LeptonSF/2016Muon_SF_ISO.root:NUM_TightRelIso_DEN_TightIDandIPCut_eta_pt
  electron: 
  - LeptonSF/2016Electron_SF_RECO.root:EGamma_SF2D 
  - LeptonSF/2016Electron_SF_IDISO.root:EGamma_SF2D
