period: "2016"
luminosity: 35921.876  # "Golden" data from 07Aug2017 re-reconstruction

dataset_stems:
- samples_2016.yaml

l1t_prefiring: true

pileup_weight:
  data_profile: /pnfs/iihe/cms/store/group/HZZ2l2nu/Bonzais/Catalogs/September2018_newIDIso_v2/pileup_2016_certified.root
  default_sim_profile: /pnfs/iihe/cms/store/group/HZZ2l2nu/Bonzais/Catalogs/September2018_newIDIso_v2/pileup_RunIISummer16.root

jets:
  # Selecting loose working point for jet ID
  jet_id_bit: 0
  min_pt: 30
  max_abs_eta: 4.7
  corrections:
    sim:
    - levels:
      - JERC/Summer16_07Aug2017_V11_MC_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017_V11_MC_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017_V11_MC_L3Absolute_AK4PFchs.txt
    data:
    - run_range: [272007, 276811]  # 2016BCD
      levels:
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer16_07Aug2017BCD_V11_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [276831, 278801]  # 2016EF1
      levels:
      - JERC/Summer16_07Aug2017EF_V11_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017EF_V11_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017EF_V11_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer16_07Aug2017EF_V11_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [278802, 284044]  # 2016F2GH
      levels:
      - JERC/Summer16_07Aug2017GH_V11_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Summer16_07Aug2017GH_V11_DATA_L2Relative_AK4PFchs.txt
      - JERC/Summer16_07Aug2017GH_V11_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Summer16_07Aug2017GH_V11_DATA_L2L3Residual_AK4PFchs.txt
    uncertainty: JERC/Summer16_07Aug2017_V11_MC_Uncertainty_AK4PFchs.txt
  resolution:
    sim_resolution: JERC/Summer16_25nsV1_MC_PtResolution_AK4PFchs.txt
    scale_factors: JERC/Summer16_25nsV1_MC_SF_AK4PFchs.txt

b_tagger:
  # Tag hreshold and SF are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation2016Legacy?rev=13
  branch_name: Jet_btagDeepFlavB
  tag_threshold: 0.0614
  # Thresholds below are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation80XReReco?rev=14#AK4_jets
  min_pt: 20
  max_abs_eta: 2.4

b_tag_weight:
  scale_factors: BTag/DeepJet_2016LegacySF_WP_V1.csv
  efficiency: BTag/btagging_efficiencies_deep2016.root

lepton_efficiency:
  muon: 
  - LeptonSF/2016Muon_SF_ID.root:NUM_TightID_DEN_genTracks_eta_pt
  - LeptonSF/2016Muon_SF_ISO.root:NUM_TightRelIso_DEN_TightIDandIPCut_eta_pt
  electron: 
  - LeptonSF/2016Electron_SF_RECO.root:EGamma_SF2D 
  - LeptonSF/2016Electron_SF_IDISO.root:EGamma_SF2D

photon_triggers:
  - name: HLT_Photon22_R9Id90_HE10_IsoM
    prescale: 1851.9 #1./(1.-0.99946)
    #precales are taken from http://homepage.iihe.ac.be/~mmahdavi/Analysis/trigsLums/trigsLumis_2016
    threshold: 24.2
    #Take 10% more, so that we are on the plateau (the pT in the name is the one at the middle of the turn-on curve, so at 50% efficiency).
  - name: HLT_Photon30_R9Id90_HE10_IsoM
    prescale: 367.65 #1./(1.-0.99728)
    threshold: 33.
  - name: HLT_Photon36_R9Id90_HE10_IsoM
    prescale: 164.47 #1./(1.-0.99392)
    threshold: 39.3
  - name: HLT_Photon50_R9Id90_HE10_IsoM
    prescale: 71.736 #1./(1.-0.98606)
    threshold: 55.
  - name: HLT_Photon75_R9Id90_HE10_IsoM
    prescale: 13.978 #1./(1.-0.92846)
    threshold: 82.5
  - name: HLT_Photon90_R9Id90_HE10_IsoM
    prescale: 6.9483 #1./(1.-0.85608)
    threshold: 99.
  - name: HLT_Photon120_R9Id90_HE10_IsoM
    prescale: 2.4773 #1./(1.-0.59633)
    threshold: 132.
  - name: HLT_Photon165_R9Id90_HE10_IsoM
    prescale: 1.
    threshold: 181.5

