period: "2017"
luminosity: 41529.5488 # "Golden" data from https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions17/13TeV/Final/Cert_294927-306462_13TeV_PromptReco_Collisions17_JSON.txt

dataset_stems:
- samples_2016.yaml
- samples_VBF_2017.yaml

l1t_prefiring: true

pileup_weight:
  data_profile: /pnfs/iihe/cms/store/group/HZZ2l2nu/Production/2019-11-01_2017/pileup/pileup_profiles_data.root
  sim_profiles: /pnfs/iihe/cms/store/group/HZZ2l2nu/Production/2019-11-01_2017/pileup/pileup_profiles_sim.root

selection_cuts:
  z_mass_window: 15.0
  min_pt_ll: 55.0
  min_dphi_ll_ptmiss: 0.5
  min_dphi_jet_ptmiss: 0.5

jets:
  # Selecting tightLepVeto working point for jet ID as recommended here https://hypernews.cern.ch/HyperNews/CMS/get/jet-algorithms/462/3/1.html
  jet_id_bit: 2
  min_pt: 30
  max_abs_eta: 4.7
  corrections:
    sim:
    - levels:
      - JERC/Fall17_17Nov2017_V32_MC_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017_V32_MC_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017_V32_MC_L3Absolute_AK4PFchs.txt
    data:
    - run_range: [297046, 299329]  # 2017B
      levels:
      - JERC/Fall17_17Nov2017B_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017B_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017B_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017B_V32_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [299368, 302029]  # 2017C
      levels:
      - JERC/Fall17_17Nov2017C_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017C_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017C_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017C_V32_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [302030, 304797]  # 2017DE
      levels:
      - JERC/Fall17_17Nov2017DE_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017DE_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017DE_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017DE_V32_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [305040, 306462]  # 2017F
      levels:
      - JERC/Fall17_17Nov2017F_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017F_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017F_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017F_V32_DATA_L2L3Residual_AK4PFchs.txt
    uncertainty: JERC/Fall17_17Nov2017_V32_MC_Uncertainty_AK4PFchs.txt
  resolution:
    sim_resolution: JERC/Fall17_V3_MC_PtResolution_AK4PFchs.txt
    scale_factors: JERC/Fall17_V3_MC_SF_AK4PFchs.txt

b_tagger:
  # Tag hreshold and SF are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X?rev=34
  branch_name: Jet_btagDeepFlavB
  tag_threshold: 0.0521
  # Thresholds below are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X?rev=34
  min_pt: 20
  max_abs_eta: 2.4

b_tag_weight:
  scale_factors: BTag/DeepFlavour_94XSF_WP_V3_B_F.csv
  efficiency: BTag/btagging_efficiencies_deep2017.root

lepton_efficiency:
  muon: 
  - LeptonSF/2017Muon_SF_ID.root:NUM_TightID_DEN_genTracks_eta_pt
  - LeptonSF/2017Muon_SF_ISO.root:NUM_TightRelIso_DEN_TightIDandIPCut_eta_pt
  electron: 
  - LeptonSF/2017Electron_SF_RECO.root:EGamma_SF2D 
  - LeptonSF/2017Electron_SF_IDISO.root:EGamma_SF2D
