period: "2017"

# "Golden" data from https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions17/13TeV/ReReco/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.txt
luminosity: 41528.9954

dataset_stems:
- dataset_settings.yaml
- dataset_settings_VBF.yaml

run_sampler:
  luminosity: Lumi/lumi.yaml
  range: [294645, 306462]

l1t_prefiring: true

pileup_weight:
  data_profile: /pnfs/iihe/cms/store/group/HZZ2l2nu/Production/2020-04-13_2017-NanoAODv6/pileup/pileup_profiles_data.root
  sim_profiles: /pnfs/iihe/cms/store/group/HZZ2l2nu/Production/2020-06-02_2017-NanoAODv6-PhotonCR/pileup/pileup_profiles_sim.root

met_filters:
  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2?rev=138#2017_data
  data:
  - "Flag_goodVertices"
  - "Flag_globalSuperTightHalo2016Filter"
  - "Flag_HBHENoiseFilter"
  - "Flag_HBHENoiseIsoFilter"
  - "Flag_EcalDeadCellTriggerPrimitiveFilter"
  - "Flag_BadPFMuonFilter"
  - "Flag_eeBadScFilter"
  - "Flag_ecalBadCalibFilterV2"
  sim:
  - "Flag_goodVertices"
  - "Flag_globalSuperTightHalo2016Filter"
  - "Flag_HBHENoiseFilter"
  - "Flag_HBHENoiseIsoFilter"
  - "Flag_EcalDeadCellTriggerPrimitiveFilter"
  - "Flag_BadPFMuonFilter"
  - "Flag_ecalBadCalibFilterV2"

selection_cuts:
  z_mass_window: 15.0
  min_pt_ll: 55.0
  min_dphi_ll_ptmiss: 1.0
  min_dphi_jets_ptmiss: 0.25
  min_dphi_leptonsjets_ptmiss: 2.5

jets:
  # Use TightLepVeto working point for jet ID as recommended in https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017?rev=11
  jet_id_bit: 2
  min_pt: 30
  max_abs_eta: 4.7
  corrections:
    sim:
    - levels:
      - JERC/Fall17_17Nov2017_V32_MC_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017_V32_MC_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017_V32_MC_L3Absolute_AK4PFchs.txt
    data:
    - run_range: [297046, 299329]  # 2017B
      levels:
      - JERC/Fall17_17Nov2017B_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017B_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017B_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017B_V32_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [299368, 302029]  # 2017C
      levels:
      - JERC/Fall17_17Nov2017C_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017C_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017C_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017C_V32_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [302030, 304797]  # 2017DE
      levels:
      - JERC/Fall17_17Nov2017DE_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017DE_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017DE_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017DE_V32_DATA_L2L3Residual_AK4PFchs.txt
    - run_range: [305040, 306462]  # 2017F
      levels:
      - JERC/Fall17_17Nov2017F_V32_DATA_L1FastJet_AK4PFchs.txt
      - JERC/Fall17_17Nov2017F_V32_DATA_L2Relative_AK4PFchs.txt
      - JERC/Fall17_17Nov2017F_V32_DATA_L3Absolute_AK4PFchs.txt
      - JERC/Fall17_17Nov2017F_V32_DATA_L2L3Residual_AK4PFchs.txt
    uncertainty: JERC/Fall17_17Nov2017_V32_MC_Uncertainty_AK4PFchs.txt
  resolution:
    sim_resolution: JERC/Fall17_V3_MC_PtResolution_AK4PFchs.txt
    scale_factors: JERC/Fall17_V3_MC_SF_AK4PFchs.txt

ptmiss:
  jer: true
  pog_jets: true
  fix_ee_2017: true

b_tagger:
  # Tag hreshold and SF are taken from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X?rev=34
  branch_name: Jet_btagDeepFlavB
  tag_threshold: 0.0521
  min_pt: 20
  max_abs_eta: 2.5

b_tag_weight:
  scale_factors: BTag/DeepFlavour_94XSF_WP_V3_B_F.csv
  efficiency: BTag/btagging_efficiencies_deep2017.root

# Example for filtering based on pileup ID
# pileup_id:
#   pt_range: [15., 50.]  # https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetID?rev=61#Recommendations_for_13_TeV_data
#   abs_eta_edges: [2.5, 3.]
#   working_points: [N, T, N]
#   efficiency: PileupID/pileup_eff_nanoaodv6.xgb
#   scale_factors: PileupID/scalefactorsPUID_81Xtraining.root

lepton_efficiency:
  muon:
  - path: LeptonSF/2017/Muon_efficiencies_id_iso_2017.root:SF_Nominal_passId
    schema: [eta, pt]
    clip_pt: true
  - path: LeptonSF/2017/Muon_efficiencies_id_iso_2017.root:SF_Nominal_passId_passIso
    schema: [eta, pt]
    clip_pt: true
  electron:
  - path: LeptonSF/2017/Electron_efficiencies_id_iso_2017.root:SF_Nominal_passId
    schema: [eta, pt]
    clip_pt: true
  - path: LeptonSF/2017/Electron_efficiencies_id_iso_2017.root:SF_Nominal_passId_passIso
    schema: [eta, pt]
    clip_pt: true
  - path: LeptonSF/2017/Electron_efficiencies_tracking_2017.root:EGamma_SF2D
    schema: [eta, pt]
    clip_pt: true

photon_efficiency:
  photon:
  - PhotonSF/2017Photon_SF_ID.root:EGamma_SF2D

photon_triggers:
  triggers:
    - name: HLT_Photon50_R9Id90_HE10_IsoM
      threshold: 55.
    - name: HLT_Photon75_R9Id90_HE10_IsoM
      threshold: 82.5
    - name: HLT_Photon90_R9Id90_HE10_IsoM
      threshold: 99.
    - name: HLT_Photon120_R9Id90_HE10_IsoM
      threshold: 132.
    - name: HLT_Photon165_R9Id90_HE10_IsoM
      threshold: 181.5
    - name: HLT_Photon200
      threshold: 220.

  photon_prescale_map: Prescales/photon_prescales_2017.yaml

photon_reweighting:
  apply_nvtx_reweighting: true
  apply_pt_reweighting: true
  apply_mass_lineshape: true
  apply_mean_weights: true
  nvtx_reweighting: InstrMetReweighting/weight_nvtx_2017.root
  pt_reweighting: InstrMetReweighting/weight_pt_2017.root
  mass_lineshape: InstrMetReweighting/lineshape_mass_2017.root
  mean_weights: InstrMetReweighting/meanWeights_2017.root
