- name: EGamma
  is_sim: false

- name: SingleElectron
  is_sim: false

- name: SingleMuon
  is_sim: false

- name: DoubleEG
  is_sim: false

- name: MuonEG
  is_sim: false

- name: DoubleMuon
  is_sim: false

- name: SinglePhoton
  is_sim: false

- name: GJets_HT-40To100
  is_sim: true
  cross_section: 18650.0

- name: GJets_HT-100To200
  is_sim: true
  cross_section: 8639.0

- name: GJets_HT-200To400
  is_sim: true
  cross_section: 2173.0

- name: GJets_HT-400To600
  is_sim: true
  cross_section: 260.7

- name: GJets_HT-600ToInf
  is_sim: true
  cross_section: 86.55

- name: ZJetsToNuNu_HT-100To200
  is_sim: true
  cross_section: 271.3

- name: ZJetsToNuNu_HT-200To400
  is_sim: true
  cross_section: 72.69

- name: ZJetsToNuNu_HT-400To600
  is_sim: true
  cross_section: 9.961

- name: ZJetsToNuNu_HT-600To800
  is_sim: true
  cross_section: 2.425

- name: ZJetsToNuNu_HT-800To1200
  is_sim: true
  cross_section: 1.1796

- name: ZJetsToNuNu_HT-1200To2500
  is_sim: true
  cross_section: 1.076

- name: ZJetsToNuNu_HT-2500ToInf
  is_sim: true
  cross_section: 0.005609

- name: ZGTo2NuG
  is_sim: true
  cross_section: 29.93 # XSDB

- name: WJetsToLNu_LO
  is_sim: true
  cross_section: 53940.0

- name: WGToLNuG_LO
  is_sim: true
  cross_section: 411.2  # XSDB
  max_ptgamma: 130

- name: WGToLNuG_PtG-130
  is_sim: true
  cross_section: 1.029  # XSDB
  min_ptgamma: 130
  max_ptgamma: 300

- name: WGToLNuG_PtG-300
  is_sim: true
  cross_section: 0.0709  # XSDB
  min_ptgamma: 300
  max_ptgamma: 500

- name: WGToLNuG_PtG-500
  is_sim: true
  cross_section: 0.009647  # XSDB
  min_ptgamma: 500

- name: DYJetsToLL
  is_sim: true
  cross_section: 5379.0  # XSDB

- name: DYJetsToLL-amcatnlo
  is_sim: true
  cross_section: 6424.0  # XSDB

- name: TTGJets
  is_sim: true
  cross_section: 3.774  # XSDB

- name: ZGTo2LG
  is_sim: true
  cross_section: 51.53  # XSDB