# All cross section values are placeholder.

- name: VBFToContinToZZTo2l2nu
  is_sim: true
  cross_section: 0.001

- name: VBFToContinToZZTo2E2Nue_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToContinToZZTo2E2Num_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToContinToZZTo2E2Nut_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToContinToZZTo2Mu2Nue_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToContinToZZTo2Mu2Num_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToContinToZZTo2Mu2Nut_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToHToZZTo2E2Nue_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToHToZZTo2E2Num_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToHToZZTo2E2Nut_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToHToZZTo2Mu2Nue_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToHToZZTo2Mu2Num_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToHToZZTo2Mu2Nut_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToZZTo2E2Nue_BSI_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToZZTo2E2Num_BSI_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToZZTo2E2Nut_BSI_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToZZTo2Mu2Nue_BSI_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToZZTo2Mu2Num_BSI_Phantom
  is_sim: true
  cross_section: 0.001

- name: VBFToZZTo2Mu2Nut_BSI_Phantom
  is_sim: true
  cross_section: 0.001

