- name: EGamma
  is_sim: false

- name: SingleElectron
  is_sim: false

- name: SingleMuon
  is_sim: false

- name: DoubleEG
  is_sim: false

- name: MuonEG
  is_sim: false

- name: DoubleMuon
  is_sim: false

- name: SinglePhoton
  is_sim: false

- name: DYJetsToLL_M-50
  is_sim: true
  cross_section: 6077.22  # NNLO, https://twiki.cern.ch/twiki/bin/view/CMS/StandardModelCrossSectionsat13TeV?rev=27

- name: DYJetsToLL
  is_sim: true
  cross_section: 5379.0  

- name: DYJetsToLL-amcatnlo
  is_sim: true
  cross_section: 6424.0  

# A fake dataset used in the NRB analysis. Produced by filtering
# DYJetsToLL_M-50.
- name: DYJetsToTauTau_M-50
  is_sim: true
  cross_section: 6077.22  # Same as for DYJetsToLL_M-50

- name: GJets_HT-40To100
  is_sim: true
  cross_section: 20790.0  # LO, XSDB
  gjets_lo: true

- name: GJets_HT-100To200
  is_sim: true
  cross_section: 9197.0  # LO, XSDB
  gjets_lo: true

- name: GJets_HT-200To400
  is_sim: true
  cross_section: 2317.0  # LO, XSDB
  gjets_lo: true

- name: GJets_HT-400To600
  is_sim: true
  cross_section: 276.9  # LO, XSDB
  gjets_lo: true

- name: GJets_HT-600ToInf
  is_sim: true
  cross_section: 94.28  # LO, XSDB
  gjets_lo: true

- name: GluGluHToZZTo2L2Nu_M800
  is_sim: true
  cross_section: 0.001346
  k_factor: ggF
  zz_2l2nu: true

- name: GluGluToContinToZZTo2e2nu
  is_sim: true
  cross_section: 0.0171871  # https://twiki.cern.ch/twiki/bin/view/CMS/HZZ2L2NuSamplesGluonFusionMCFM?rev=5#Cross_sections
  k_factor: ggF
  zz_2l2nu: true

- name: GluGluToContinToZZTo2mu2nu
  is_sim: true
  cross_section: 0.0171871  # https://twiki.cern.ch/twiki/bin/view/CMS/HZZ2L2NuSamplesGluonFusionMCFM?rev=5#Cross_sections
  k_factor: ggF
  zz_2l2nu: true

- name: GGToHToZZTo2E2Nu
  is_sim: true
  cross_section: 0.0058257  # https://twiki.cern.ch/twiki/bin/view/CMS/HZZ2L2NuSamplesGluonFusionMCFM?rev=5#Cross_sections
  k_factor: ggF
  zz_2l2nu: true

- name: GGToHToZZTo2Mu2Nu
  is_sim: true
  cross_section: 0.0058257  # https://twiki.cern.ch/twiki/bin/view/CMS/HZZ2L2NuSamplesGluonFusionMCFM?rev=5#Cross_sections
  k_factor: ggF
  zz_2l2nu: true

- name: GGToZZTo2E2Nu_BSI
  is_sim: true
  cross_section: 0.0214946  # https://twiki.cern.ch/twiki/bin/view/CMS/HZZ2L2NuSamplesGluonFusionMCFM?rev=5#Cross_sections
  k_factor: ggF
  zz_2l2nu: true

- name: GGToZZTo2Mu2Nu_BSI
  is_sim: true
  cross_section: 0.0214946  # https://twiki.cern.ch/twiki/bin/view/CMS/HZZ2L2NuSamplesGluonFusionMCFM?rev=5#Cross_sections
  k_factor: ggF
  zz_2l2nu: true

- name: QCD_HT50to100
  is_sim: true
  cross_section: 246300000.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT100to200
  is_sim: true
  cross_section: 28060000.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT200to300
  is_sim: true
  cross_section: 1710000.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT300to500
  is_sim: true
  cross_section: 347500.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT500to700
  is_sim: true
  cross_section: 32060.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT700to1000
  is_sim: true
  cross_section: 6829.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT1000to1500
  is_sim: true
  cross_section: 1207.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT1500to2000
  is_sim: true
  cross_section: 120.0  # LO, XSDB
  mc_qcd: true

- name: QCD_HT2000toInf
  is_sim: true
  cross_section: 25.25  # LO, XSDB
  mc_qcd: true

- name: ST_s-channel
  is_sim: true
  # Cross section computed as NLO cross section of 10.32 pb from [1] multiplied
  # by a branching fraction of 3 * 0.1086
  # [1] https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopRefXsec?rev=34
  cross_section: 3.362

- name: ST_t-channel_antitop
  is_sim: true
  cross_section: 80.95  # NLO, https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopRefXsec?rev=34

- name: ST_t-channel_top
  is_sim: true
  cross_section: 136.02  # NLO, https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopRefXsec?rev=34

- name: ST_tW_antitop
  is_sim: true
  # Cross section computed as approx. NNLO cross section of 71.7 pb from [1]
  # divided by 2
  # [1] https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopRefXsec?rev=34
  cross_section: 35.85

- name: ST_tW_top
  is_sim: true
  # Cross section computed as approx. NNLO cross section of 71.7 pb from [1]
  # divided by 2
  # [1] https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopRefXsec?rev=34
  cross_section: 35.85

- name: TGJets
  is_sim: true
  # Cross section computed as the inclusive NLO cross section of 2.967 pb
  # from [1] multiplied by the branching fraction of 3 * 0.1086. This matches
  # the cross section of 0.989 pb reported in McM [2], while the one in XSDB is
  # way off.
  # [1] https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153
  # [2] https://cms-pdmv.cern.ch/mcm/requests?prepid=TOP-RunIISummer15wmLHEGS-00001
  cross_section: 0.967

- name: TTGJets
  is_sim: true
  cross_section: 3.697  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: TT
  is_sim: true
  cross_section: 831.76  # NNLO, https://twiki.cern.ch/twiki/bin/view/LHCPhysics/TtbarNNLO?rev=16

- name: TTTo2L2Nu
  is_sim: true
  # Cross section computed as the inclusive NNLO cross section of 831.76 pb
  # from [1] multiplied by the branching fraction (3 * 0.1086)^2.
  # [1] https://twiki.cern.ch/twiki/bin/view/LHCPhysics/TtbarNNLO?rev=16
  cross_section: 88.288

- name: TTWJetsToLNu
  is_sim: true
  cross_section: 0.2043  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: TTZToLLNuNu_M-10
  is_sim: true
  cross_section: 0.2529  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: WGToLNuG
  is_sim: true
  cross_section: 489  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: WGToLNuG_LO  # for 2017/2018
  is_sim: true
  cross_section: 489  # For now, reweight to NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153
  wgamma_lnugamma: inclusive

- name: WGToLNuG_PtG-130  # for 2017/2018
  is_sim: true
  cross_section: 1.119  # Unknown accuracy, XSDB
  wgamma_lnugamma: pt130

- name: WGToLNuG_PtG-500  # for 2017/2018
  is_sim: true
  cross_section: 0.009237  # Unknown accuracy, XSDB
  wgamma_lnugamma: pt500

- name: WJetsToLNu
  is_sim: true
  # Cross section computed as NNLO cross section of 20508.9 pb from [1]
  # multiplied by 3
  # [1] https://twiki.cern.ch/twiki/bin/view/CMS/StandardModelCrossSectionsat13TeV?rev=27
  cross_section: 61526.7

- name: WJetsToLNu_LO
  is_sim: true
  cross_section: 61526.7  # Same as for WJetsToLNu
  me_kin_filter:  # Removes overlap with Ht-binned samples
    variable: Ht
    range: [0., 100.]

- name: WJetsToLNu_HT-100To200
  is_sim: true
  # Cross sections for this and other Ht-binned W+jets samples have been
  # computed by rescaling corresponding LO cross sections by the ratio between
  # NNLO and LO cross sections for the inclusive sample (which is around 1.21)
  cross_section: 1627.45

- name: WJetsToLNu_HT-200To400
  is_sim: true
  cross_section: 435.23699999999997

- name: WJetsToLNu_HT-400To600
  is_sim: true
  cross_section: 59.181099999999994

- name: WJetsToLNu_HT-600To800
  is_sim: true
  cross_section: 14.5805

- name: WJetsToLNu_HT-800To1200
  is_sim: true
  cross_section: 6.656210000000001

- name: WJetsToLNu_HT-1200To2500
  is_sim: true
  cross_section: 1.6080899999999998

- name: WJetsToLNu_HT-2500ToInf
  is_sim: true
  cross_section: 0.0389136

- name: WWTo2L2Nu
  is_sim: true
  cross_section: 12.178  # NNLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: WWW
  is_sim: true
  cross_section: 0.2086  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: WWZ
  is_sim: true
  cross_section: 0.1651  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: WZTo2L2Q
  is_sim: true
  cross_section: 5.595  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: WZTo3LNu
  is_sim: true
  cross_section: 4.4296  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=1535
  ew_correction: WZ

- name: WZZ
  is_sim: true
  cross_section: 0.0556  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=1535

- name: ZGTo2LG
  is_sim: true
  cross_section: 117.864  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZGTo2LG_PtG-130
  is_sim: true
  cross_section: 0.1594  # Unknown accuracy, XSDB

- name: ZGTo2NuG
  is_sim: true
  cross_section: 28.04  # Unknown accuracy, XSDB
  zgamma_2nugamma: inclusive

- name: ZGTo2NuG_PtG-130
  is_sim: true
  cross_section: 0.2768  # Unknown accuracy, XSDB
  zgamma_2nugamma: pt130

- name: ZJetsToNuNu_HT-100To200
  is_sim: true
  cross_section: 280.35  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZJetsToNuNu_HT-200To400
  is_sim: true
  cross_section: 77.67  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZJetsToNuNu_HT-400To600
  is_sim: true
  cross_section: 10.73  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZJetsToNuNu_HT-600To800
  is_sim: true
  cross_section: 2.559  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZJetsToNuNu_HT-800To1200
  is_sim: true
  cross_section: 1.1796  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZJetsToNuNu_HT-1200To2500
  is_sim: true
  cross_section: 0.28833  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZJetsToNuNu_HT-2500ToInf
  is_sim: true
  cross_section: 0.006945  #LO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZZTo2L2Nu
  is_sim: true
  cross_section: 0.564  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153
  ew_correction: ZZ
  zz_2l2nu: true

- name: ZZTo2L2Q
  is_sim: true
  cross_section: 3.22  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: ZZTo4L
  is_sim: true
  cross_section: 1.212  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

# A fake dataset used in the NRB analysis. Produced by filtering ZZTo2L2Nu.
- name: ZZToTauTau2Nu
  is_sim: true
  cross_section: 0.564  # Same as for ZZTo2L2Nu
  zz_2l2nu: true

# A fake dataset used in the NRB analysis. Produced by filtering ZZTo2L2Q.
- name: ZZToTauTau2Q
  is_sim: true
  cross_section: 3.22  # Same as for ZZTo2L2Q

- name: ZZZ
  is_sim: true
  cross_section: 0.01398  # NLO, https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=153

- name: DYJetsToLL_M50_HT100to200
  is_sim: true
  cross_section: 139.2

- name: DYJetsToLL_M50_HT200to400
  is_sim: true
  cross_section: 38.4  

- name: DYJetsToLL_M50_HT400to600
  is_sim: true
  cross_section: 5.174

- name: DYJetsToLL_M50_HT600to800
  is_sim: true
  cross_section: 1.258

- name: DYJetsToLL_M50_HT800to1200
  is_sim: true
  cross_section: 0.5598

- name: DYJetsToLL_M50_HT1200to2500
  is_sim: true
  cross_section: 0.1305 

- name: DYJetsToLL_M50_HT2500toInf
  is_sim: true
  cross_section: 0.002997

- name: DYJetsToLL_PtZ-0To50
  is_sim: true
  cross_section: 1485.0 

- name: DYJetsToLL_PtZ-100To250
  is_sim: true
  cross_section: 97.2 

- name: DYJetsToLL_PtZ-250To400
  is_sim: true
  cross_section: 3.701  

- name: DYJetsToLL_PtZ-400To650
  is_sim: true
  cross_section: 0.5086 

- name: DYJetsToLL_PtZ-50To100
  is_sim: true
  cross_section: 397.4

- name: DYJetsToLL_PtZ-650ToInf
  is_sim: true
  cross_section: 0.04728  

- name: WZ2JetsTo3LNu
  is_sim: true
  cross_section: 0.01353  

- name: WZTo1L1Nu2Q
  is_sim: true
  cross_section: 9.119
