- name: EGamma
  is_sim: false

- name: SingleElectron
  is_sim: false

- name: SingleMuon
  is_sim: false

- name: DoubleEG
  is_sim: false

- name: MuonEG
  is_sim: false

- name: DoubleMuon
  is_sim: false

- name: SinglePhoton
  is_sim: false

- name: ZJetsToNuNu_HT-100To200
  is_sim: true
  cross_section: 271.3

- name: ZJetsToNuNu_HT-200To400
  is_sim: true
  cross_section: 72.69

- name: ZJetsToNuNu_HT-400To600
  is_sim: true
  cross_section: 9.961

- name: ZJetsToNuNu_HT-600To800
  is_sim: true
  cross_section: 2.425

- name: ZJetsToNuNu_HT-800To1200
  is_sim: true
  cross_section: 1.1796

- name: ZJetsToNuNu_HT-1200To2500
  is_sim: true
  cross_section: 1.076

- name: ZJetsToNuNu_HT-2500ToInf
  is_sim: true
  cross_section: 0.005609

- name: ZGTo2NuG
  is_sim: true
  cross_section: 29.93 # XSDB

- name: WJetsToLNu_LO
  is_sim: true
  cross_section: 53940.0
  me_kin_filter:  # Removes overlap with Ht-binned samples
    variable: Ht
    range: [0., 100.]

- name: WJetsToLNu_HT-100To200
  is_sim: true
  cross_section: 1244.0

- name: WJetsToLNu_HT-200To400
  is_sim: true
  cross_section: 337.8

- name: WJetsToLNu_HT-400To600
  is_sim: true
  cross_section: 44.93

- name: WJetsToLNu_HT-600To800
  is_sim: true
  cross_section: 11.19

- name: WJetsToLNu_HT-800To1200
  is_sim: true
  cross_section: 4.926

- name: WJetsToLNu_HT-1200To2500
  is_sim: true
  cross_section: 1.152

- name: WJetsToLNu_HT-2500ToInf
  is_sim: true
  cross_section: 0.02646

- name: WJetsToLNu_NLO
  is_sim: true
  cross_section: 66680.0

- name: DYJetsToLL
  is_sim: true
  cross_section: 5379.0  # XSDB

- name: DYJetsToLL-amcatnlo
  is_sim: true
  cross_section: 6424.0  # XSDB

- name: TTGJets
  is_sim: true
  cross_section: 3.774  # XSDB

- name: ZGTo2LG
  is_sim: true
  cross_section: 51.53  # XSDB