# Groups of datasets to be merged in harvesting. The source datasets do not have
# to be present.

TT: [TT, TTTo2L2Nu]  # To have consistent naming across different years
ST_tW: [ST_tW_top, ST_tW_antitop]
ST_t-channel: [ST_t-channel_top, ST_t-channel_antitop]
WJets: [
  WJetsToLNu_LO, WJetsToLNu_HT-100To200, WJetsToLNu_HT-200To400,
  WJetsToLNu_HT-400To600, WJetsToLNu_HT-600To800, WJetsToLNu_HT-800To1200,
  WJetsToLNu_HT-1200To2500, WJetsToLNu_HT-2500ToInf
]
GJets: [
  GJets_HT-40To100, GJets_HT-100To200, GJets_HT-200To400, GJets_HT-400To600,
  GJets_HT-600ToInf
]
QCD: [
  QCD_HT100to200, QCD_HT200to300, QCD_HT300to500, QCD_HT500to700,
  QCD_HT700to1000, QCD_HT1000to1500, QCD_HT1500to2000, QCD_HT2000toInf
]
WGToLNuG: [WGToLNuG, WGToLNuG_LO, WGToLNuG_PtG-130, WGToLNuG_PtG-500]
ZGTo2LG: [ZGTo2LG, ZGTo2LG_PtG-130] # For consistent naming
ZJetsToNuNu: [
  ZJetsToNuNu_HT-100To200, ZJetsToNuNu_HT-200To400, ZJetsToNuNu_HT-400To600,
  ZJetsToNuNu_HT-600To800, ZJetsToNuNu_HT-800To1200, ZJetsToNuNu_HT-1200To2500,
  ZJetsToNuNu_HT-2500ToInf
]

GGToZZ: [GluGluToContinToZZTo2e2nu, GluGluToContinToZZTo2mu2nu]
GGToHToZZ: [GGToHToZZTo2E2Nu, GGToHToZZTo2Mu2Nu]
GGToZZ_BSI: [GGToZZTo2E2Nu_BSI, GGToZZTo2Mu2Nu_BSI]

VBFToZZ: [VBFToContinToZZTo2l2nu]
VBFToZZ_Phantom: [
  VBFToContinToZZTo2E2Nue_Phantom, VBFToContinToZZTo2E2Num_Phantom,
  VBFToContinToZZTo2E2Nut_Phantom, VBFToContinToZZTo2Mu2Nue_Phantom,
  VBFToContinToZZTo2Mu2Num_Phantom, VBFToContinToZZTo2Mu2Nut_Phantom
]
VBFToHToZZ_Phantom: [
  VBFToHToZZTo2E2Nue_Phantom, VBFToHToZZTo2E2Num_Phantom,
  VBFToHToZZTo2E2Nut_Phantom, VBFToHToZZTo2Mu2Nue_Phantom,
  VBFToHToZZTo2Mu2Num_Phantom, VBFToHToZZTo2Mu2Nut_Phantom
]
VBFToZZ_BSI_Phantom: [
  VBFToZZTo2E2Nue_BSI_Phantom, VBFToZZTo2E2Num_BSI_Phantom,
  VBFToZZTo2E2Nut_BSI_Phantom, VBFToZZTo2Mu2Nue_BSI_Phantom,
  VBFToZZTo2Mu2Num_BSI_Phantom, VBFToZZTo2Mu2Nut_BSI_Phantom
]

