selections:

- formula: "abs(probe_eta) <= 1.4442 && event_cat == 0"
  weight: weight
  tag: barrel_ee
  label: "barrel_ee"

- formula: "abs(probe_eta) <= 1.4442 && event_cat == 1"
  weight: weight
  tag: barrel_egamma
  label: "barrel_egamma"

- formula: "abs(probe_eta) >= 1.5660 && event_cat == 0"
  weight: weight
  tag: endcap_ee
  label: "endcap_ee"

- formula: "abs(probe_eta) >= 1.5660 && event_cat == 1"
  weight: weight
  tag: endcap_egamma
  label: "endcap_egamma"


samples:
  path_prefix: ""
  data:
    files: [Data]
  simulation:
    - label: "$W\\gamma \\to \\ell\\nu\\gamma$"
      files: [WGToLNuG]
      color: blueviolet
    - label: "$t\\bar t$"
      files: [TTJets]
      color: greenyellow
    - label: "$\\gamma + $jets"
      files: [GJets]
      color: darkorange
    - label: "$WW(\\to 2\\ell 2\\nu)$"
      files: [WWTo2L2Nu]
      color: lightseagreen
    - label: "Drell-Yan"
      files: [DYJetsToLL_PtZ]
      color: steelblue


variables:
- formula: "tot_mass"
  binning:
    default:
      range: [76., 106.]
      bins: 30
  x_scale: linear
  label: "$m_\\mathrm{tot}$"
  unit: GeV
  tag: tot_mass
- formula: "probe_pt"
  binning:
    default:
      range: [55., 250.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{\\mathrm{probe}}$"
  unit: GeV
  tag: pt_probe
- formula: "ptmiss"
  binning:
    default:
      range: [10., 1000.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{miss}$"
  unit: GeV
  tag: pt_miss
