# This is the configuration file to get plots from the PhotonTrees analysis.

selections:
- formula: "ptmiss > 80."
  weight: weight
  weight_data: trigger_weight
  tag: baseline
  label: "single $\\gamma$, baseline selection"

- formula: "ptmiss > 80. && jet_cat == 0"
  weight: weight
  weight_data: trigger_weight
  tag: baseline_eq0jet
  label: "single $\\gamma$, baseline selection, $0j$"

- formula: "ptmiss > 80. && jet_cat == 1"
  weight: weight
  weight_data: trigger_weight
  tag: baseline_geq1jet
  label: "single $\\gamma$, baseline selection, $\\geqslant 1j$"

- formula: "ptmiss > 80. && jet_cat == 2"
  weight: weight
  weight_data: trigger_weight
  tag: baseline_vbf
  label: "single $\\gamma$, baseline selection, VBF"

- formula: "ptmiss < 125."
  weight: weight
  weight_data: trigger_weight
  tag: for_reweighting
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV"

- formula: "ptmiss < 125. && jet_cat == 0"
  weight: weight
  weight_data: trigger_weight
  tag: for_reweighting_eq0jet
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $0j$"

- formula: "ptmiss < 125. && jet_cat == 1"
  weight: weight
  weight_data: trigger_weight
  tag: for_reweighting_geq1jet
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $\\geqslant 1j$"

- formula: "ptmiss < 125. && jet_cat == 2"
  weight: weight
  weight_data: trigger_weight
  tag: for_reweighting_vbf
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, VBF"

- formula: "ptmiss > 125."
  weight: weight
  weight_data: trigger_weight
  tag: signal_region
  label: "single $\\gamma$, signal region"

- formula: "ptmiss > 125. && jet_cat == 0"
  weight: weight
  weight_data: trigger_weight
  tag: signal_region_eq0jet
  label: "single $\\gamma$, signal region, $0j$"

- formula: "ptmiss > 125. && jet_cat == 1"
  weight: weight
  weight_data: trigger_weight
  tag: signal_region_geq1jet
  label: "single $\\gamma$, signal region, $\\geqslant 1j$"

- formula: "ptmiss > 125. && jet_cat == 2"
  weight: weight
  weight_data: trigger_weight
  tag: signal_region_vbf
  label: "single $\\gamma$, signal region, VBF"

- formula: "ptmiss < 125. && photon_pt >= 55. && photon_pt < 82.5"
  weight: weight
  weight_data: trigger_weight
#  weight: weight/71.736
  tag: bin1_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $55 < p_\\mathrm{T}^{\\gamma} < 82.5$"

- formula: "ptmiss < 125. && photon_pt >= 82.5 && photon_pt < 99."
  weight: weight
  weight_data: trigger_weight
#  weight: weight/13.978
  tag: bin2_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $82.5 < p_\\mathrm{T}^{\\gamma} < 99$"

- formula: "ptmiss < 125. && photon_pt >= 99. && photon_pt < 132."
  weight: weight
  weight_data: trigger_weight
#  weight: weight/6.9483
  tag: bin3_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $99 < p_\\mathrm{T}^{\\gamma} < 132$"

- formula: "ptmiss < 125. && photon_pt >= 132. && photon_pt < 181.5"
  weight: weight
  weight_data: trigger_weight
#  weight: weight/2.4773
  tag: bin4_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $132 < p_\\mathrm{T}^{\\gamma} < 181.5$"

- formula: "ptmiss < 125. && photon_pt >= 181.5"
  weight: weight
  weight_data: trigger_weight
  tag: bin5_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $p_\\mathrm{T}^{\\gamma} > 181.5$"

- formula: "ptmiss > 125. && photon_pt >= 55. && photon_pt < 82.5"
  weight: "weight * photon_reweighting"
  weight_data: "trigger_weight * photon_reweighting"
  tag: bin1_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $55 < p_\\mathrm{T}^{\\gamma} < 82.5$"

- formula: "ptmiss > 125. && photon_pt >= 82.5 && photon_pt < 99."
  weight: "weight * photon_reweighting"
  weight_data: "trigger_weight * photon_reweighting"
  tag: bin2_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $82.5 < p_\\mathrm{T}^{\\gamma} < 99$"

- formula: "ptmiss > 125. && photon_pt >= 99. && photon_pt < 132."
  weight: "weight * photon_reweighting"
  weight_data: "trigger_weight * photon_reweighting"
  tag: bin3_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $99 < p_\\mathrm{T}^{\\gamma} < 132$"

- formula: "ptmiss > 125. && photon_pt >= 132. && photon_pt < 181.5"
  weight: "weight * photon_reweighting"
  weight_data: "trigger_weight * photon_reweighting"
  tag: bin4_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $132 < p_\\mathrm{T}^{\\gamma} < 181.5$"

- formula: "ptmiss > 125. && photon_pt >= 181.5"
  weight: "weight * photon_reweighting"
  weight_data: "trigger_weight * photon_reweighting"
  tag: bin5_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $p_\\mathrm{T}^{\\gamma} > 181.5$"

samples:
  path_prefix: ""
  data:
    files: [Data]
  simulation:
  - label: "$Z\\gamma \\to 2\\nu\\gamma$"
    files: [ZGTo2NuG, ZGTo2NuG_PtG-130]
    color: gold
  - label: "$Z\\gamma \\to 2\\ell\\gamma$"
    files: [ZGTo2LG]
    color: maroon
  - label: "$W\\gamma \\to \\ell\\nu\\gamma$"
    files: [WGToLNuG]
    color: blueviolet
  - label: "$t\\gamma$, $tt\\gamma$"
    files: [TTGJets, TGJets]
    color: limegreen
  - label: "$\\gamma + $ jets"
    files: [GJets]
    color: darkorange
  - label: "$W + $ jets $ \\to \\ell\\nu$"
    files: [WJets]
    color: palevioletred
  - label: "QCD (HT > 100)"
    files: [QCD]
    color: darkgray

variables:
- formula: "photon_pt"
  binning:
    default:
      range: [55., 1400.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma
- formula: "ptmiss"
  binning:
    default:
      range: [10., 1000.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{miss}$"
  unit: GeV
  tag: pt_miss
- formula: "photon_eta"
  binning:
    default:
      range: [-2., 2.]
      bins: 40
  x_scale: linear
  label: "$\\eta^{\\gamma}$"
  unit: 
  tag: eta_gamma
- formula: "photon_phi"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$\\phi^{\\gamma}$"
  unit: 
  tag: phi_gamma
- formula: "mT"
  binning:
    default:
      range: [200., 2000.]
      bins: 20
  x_scale: log
  label: "$m_\\mathrm{T}$"
  unit: GeV
  tag: mt
- formula: "num_pv_good"
  binning:
    default:
      range: [0., 75.]
      bins: 20
  x_scale: linear
  label: "Number of good vertices"
  unit:
  tag: numpvgood
- formula: "photon_reweighting"
  binning:
    default:
      range: [0., 0.2]
      bins: 10
  x_scale: linear
  label: "Photon reweighting factor"
  unit:
  tag: photonreweighting

