# This is the configuration file to get plots from the ZGammaTrees analysis.

selections:
- formula: "ptmiss >= 0."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: baseline
  label: "baseline selection"

- formula: "ptmiss < 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_l120
  label: "$p_\\mathrm{T}^\\mathrm{miss} < 120.$"

- formula: "ptmiss >= 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_geq120
  label: "$p_\\mathrm{T}^\\mathrm{miss} \\geq 120.$"

- formula: "jet_size >= 2"
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: geq2jet
  label: "$\\geq$ 2jet"

# - formula: "jet_size >= 2 && ptmiss >= 120. && photon_eta >= 1.48 && photon_eta <= 1.58"
#   weight: weight
#   weight_data: trigger_weight * beam_halo_weight
#   tag: hotspot
#   label: "$\\geq$ 2jet, $p_\\mathrm{T}^\\mathrm{miss} \\geq 120.$, $1.48 \\leq \\eta^{\\gamma} \\leq 1.58$"

samples:
  path_prefix: ""
  data:
    files: [Data]
  simulation:
    - label: "$Z\\gamma \\to 2\\nu\\gamma$"
      files: [ZGTo2NuG, ZNuNuGJets]
      color: gold
    # - label: "$Z(\\to 2\\nu) + $jets\n(HT > 100)"
    #   files: [ZJetsToNuNu]
    #   color: steelblue
    - label: "$W\\gamma \\to \\ell\\nu\\gamma$"
      files: [WGToLNuG]
      color: blueviolet
    - label: "$t\\gamma$, $tt\\gamma$"
      files: [TTGJets, TGJets]
      color: limegreen
    - label: "$\\gamma + $jets"
      files: [GJets]
      color: darkorange
    - label: "WJetsToLNu\n(LO)"
      files: [WJets]
      color: palevioletred
    - label: "QCD (HT > 100)"
      files: [QCD]
      color: darkgray

variables:
- formula: "photon_pt"
  binning:
    default:
      range: [20., 1400.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma
- formula: "photon_pt"
  binning:
    default:
      range: [20., 720.]
      bins: 20
  x_scale: linear
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma_linear
- formula: "jet_size"
  binning:
    default:
      range: [0, 6]
      bins: 6
  x_scale: linear
  label: "$N_{jets}$"
  unit: 
  tag: njets
- formula: "ptmiss"
  binning:
    default:
      range: [10., 1000.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{miss}$"
  unit: GeV
  tag: pt_miss
- formula: "ptmiss_phi"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$p_\\mathrm{T}^{miss}$"
  unit: 
  tag: phi_miss
- formula: "photon_eta"
  binning:
    default:
      range: [-2., 2.]
      bins: 40
  x_scale: linear
  label: "$\\eta^{\\gamma}$"
  unit: 
  tag: eta_gamma
- formula: "photon_phi"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$\\phi^{\\gamma}$"
  unit: 
  tag: phi_gamma
- formula: "num_pv_good"
  binning:
    default:
      range: [0., 75.]
      bins: 20
  x_scale: linear
  label: "Number of good vertices"
  unit:
  tag: numpvgood