# This is the configuration file to get plots from the PhotonTrees analysis.

selections:
- formula: "p4Miss.Pt() > 80."
  weight: weight
  weight_data: triggerWeight
  tag: baseline
  label: "single $\\gamma$, baseline selection"

- formula: "p4Miss.Pt() > 80. && jetCat == 0"
  weight: weight
  weight_data: triggerWeight
  tag: baseline_eq0jet
  label: "single $\\gamma$, baseline selection, $0j$"

- formula: "p4Miss.Pt() > 80. && jetCat == 1"
  weight: weight
  weight_data: triggerWeight
  tag: baseline_geq1jet
  label: "single $\\gamma$, baseline selection, $\\geqslant 1j$"

- formula: "p4Miss.Pt() > 80. && jetCat == 2"
  weight: weight
  weight_data: triggerWeight
  tag: baseline_vbf
  label: "single $\\gamma$, baseline selection, VBF"

- formula: "p4Miss.Pt() < 125."
  weight: weight
  weight_data: triggerWeight
  tag: for_reweighting
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV"

- formula: "p4Miss.Pt() < 125. && jetCat == 0"
  weight: weight
  weight_data: triggerWeight
  tag: for_reweighting_eq0jet
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $0j$"

- formula: "p4Miss.Pt() < 125. && jetCat == 1"
  weight: weight
  weight_data: triggerWeight
  tag: for_reweighting_geq1jet
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $\\geqslant 1j$"

- formula: "p4Miss.Pt() < 125. && jetCat == 2"
  weight: weight
  weight_data: triggerWeight
  tag: for_reweighting_vbf
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, VBF"

- formula: "p4Miss.Pt() > 125."
  weight: weight
  weight_data: triggerWeight
  tag: signal_region
  label: "single $\\gamma$, signal region"

- formula: "p4Miss.Pt() > 125. && jetCat == 0"
  weight: weight
  weight_data: triggerWeight
  tag: signal_region_eq0jet
  label: "single $\\gamma$, signal region, $0j$"

- formula: "p4Miss.Pt() > 125. && jetCat == 1"
  weight: weight
  weight_data: triggerWeight
  tag: signal_region_geq1jet
  label: "single $\\gamma$, signal region, $\\geqslant 1j$"

- formula: "p4Miss.Pt() > 125. && jetCat == 2"
  weight: weight
  weight_data: triggerWeight
  tag: signal_region_vbf
  label: "single $\\gamma$, signal region, VBF"

- formula: "p4Miss.Pt() < 125. && p4Photon.Pt() >= 55. && p4Photon.Pt() < 82.5"
  weight: weight
  weight_data: triggerWeight
#  weight: weight/71.736
  tag: bin1_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $55 < p_\\mathrm{T}^{\\gamma} < 82.5$"

- formula: "p4Miss.Pt() < 125. && p4Photon.Pt() >= 82.5 && p4Photon.Pt() < 99."
  weight: weight
  weight_data: triggerWeight
#  weight: weight/13.978
  tag: bin2_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $82.5 < p_\\mathrm{T}^{\\gamma} < 99$"

- formula: "p4Miss.Pt() < 125. && p4Photon.Pt() >= 99. && p4Photon.Pt() < 132."
  weight: weight
  weight_data: triggerWeight
#  weight: weight/6.9483
  tag: bin3_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $99 < p_\\mathrm{T}^{\\gamma} < 132$"

- formula: "p4Miss.Pt() < 125. && p4Photon.Pt() >= 132. && p4Photon.Pt() < 181.5"
  weight: weight
  weight_data: triggerWeight
#  weight: weight/2.4773
  tag: bin4_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $132 < p_\\mathrm{T}^{\\gamma} < 181.5$"

- formula: "p4Miss.Pt() < 125. && p4Photon.Pt() >= 181.5"
  weight: weight
  weight_data: triggerWeight
  tag: bin5_before
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} < 125$ GeV, $p_\\mathrm{T}^{\\gamma} > 181.5$"

- formula: "p4Miss.Pt() > 125. && p4Photon.Pt() >= 55. && p4Photon.Pt() < 82.5"
  weight: "weight * photonReweighting"
  weight_data: "triggerWeight * photonReweighting"
  tag: bin1_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $55 < p_\\mathrm{T}^{\\gamma} < 82.5$"

- formula: "p4Miss.Pt() > 125. && p4Photon.Pt() >= 82.5 && p4Photon.Pt() < 99."
  weight: "weight * photonReweighting"
  weight_data: "triggerWeight * photonReweighting"
  tag: bin2_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $82.5 < p_\\mathrm{T}^{\\gamma} < 99$"

- formula: "p4Miss.Pt() > 125. && p4Photon.Pt() >= 99. && p4Photon.Pt() < 132."
  weight: "weight * photonReweighting"
  weight_data: "triggerWeight * photonReweighting"
  tag: bin3_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $99 < p_\\mathrm{T}^{\\gamma} < 132$"

- formula: "p4Miss.Pt() > 125. && p4Photon.Pt() >= 132. && p4Photon.Pt() < 181.5"
  weight: "weight * photonReweighting"
  weight_data: "triggerWeight * photonReweighting"
  tag: bin4_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $132 < p_\\mathrm{T}^{\\gamma} < 181.5$"

- formula: "p4Miss.Pt() > 125. && p4Photon.Pt() >= 181.5"
  weight: "weight * photonReweighting"
  weight_data: "triggerWeight * photonReweighting"
  tag: bin5_after
  label: "single $\\gamma$, $p_\\mathrm{T}^\\mathrm{miss} > 125$ GeV, $p_\\mathrm{T}^{\\gamma} > 181.5$"

samples:
  path_prefix: ""
  data:
    files: [Data]
  simulation:
  - label: "$Z\\gamma \\to 2\\nu\\gamma$"
    files: [ZGTo2NuG, ZGTo2NuG_PtG-130]
    color: gold
  - label: "$Z\\gamma \\to 2\\ell\\gamma$"
    files: [ZGTo2LG]
    color: maroon
  - label: "$W\\gamma \\to \\ell\\nu\\gamma$"
    files: [WGToLNuG]
    color: blueviolet
  - label: "$t\\gamma$, $tt\\gamma$"
    files: [TTGJets, TGJets]
    color: limegreen
  - label: "$\\gamma + $ jets"
    files: [
      GJets_HT-40To100, GJets_HT-100To200, GJets_HT-200To400,
      GJets_HT-400To600, GJets_HT-600ToInf]
    color: darkorange
  - label: "$W + $ jets $ \\to \\ell\\nu$"
    files: [
      WJetsToLNu_LO, WJetsToLNu_HT-100To200,
      WJetsToLNu_HT-200To400, WJetsToLNu_HT-400To600,
      WJetsToLNu_HT-600To800, WJetsToLNu_HT-800To1200,
      WJetsToLNu_HT-1200To2500, WJetsToLNu_HT-2500ToInf]
    color: palevioletred
  - label: "QCD (HT > 100)"
    files: [
      QCD_HT100to200, QCD_HT200to300, QCD_HT300to500, 
      QCD_HT500to700, QCD_HT700to1000, QCD_HT1000to1500, QCD_HT1500to2000,
      QCD_HT2000toInf]
    color: darkgray

variables:
- formula: "p4Photon.Pt()"
  binning:
    default:
      range: [55., 1400.]
      bins: 20
  scale: log
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma
- formula: "p4Miss.Pt()"
  binning:
    default:
      range: [10., 1000.]
      bins: 20
  scale: log
  label: "$p_\\mathrm{T}^{miss}$"
  unit: GeV
  tag: pt_miss
- formula: "p4Photon.Eta()"
  binning:
    default:
      range: [-2., 2.]
      bins: 40
  scale: linear
  label: "$\\eta^{\\gamma}$"
  unit: 
  tag: eta_gamma
- formula: "p4Photon.Phi()"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  scale: linear
  label: "$\\phi^{\\gamma}$"
  unit: 
  tag: phi_gamma
- formula: "mT"
  binning:
    default:
      range: [200., 2000.]
      bins: 20
  scale: log
  label: "$m_\\mathrm{T}$"
  unit: GeV
  tag: mt
- formula: "numPVGood"
  binning:
    default:
      range: [0., 75.]
      bins: 20
  scale: linear
  label: "Number of good vertices"
  unit:
  tag: numpvgood
- formula: "photonReweighting"
  binning:
    default:
      range: [0., 0.2]
      bins: 10
  scale: linear
  label: "Photon reweighting factor"
  unit:
  tag: photonreweighting

