- name: SingleElectron
  is_sim: false

- name: SingleMuon
  is_sim: false

- name: DoubleEG
  is_sim: false

- name: MuonEG
  is_sim: false

- name: DoubleMuon
  is_sim: false

- name: SinglePhoton
  is_sim: false

- name: DYJetsToLL_M-10to50
  is_sim: true
  cross_section: 18610

- name: DYJetsToLL_M-50
  is_sim: true
  cross_section: 5765.4

- name: DYJetsToTauTau_M-10to50
  is_sim: true
  cross_section: 18610

- name: DYJetsToTauTau_M-50
  is_sim: true
  cross_section: 5765.4

- name: GJets_HT-100To200
  is_sim: true
  cross_section: 9238

- name: GJets_HT-200To400
  is_sim: true
  cross_section: 2305

- name: GJets_HT-400To600
  is_sim: true
  cross_section: 274.4

- name: GJets_HT-40To100
  is_sim: true
  cross_section: 20790

- name: GJets_HT-600ToInf
  is_sim: true
  cross_section: 93.46

- name: GJets_Pt-1000To2000
  is_sim: true
  cross_section: 0.02092

- name: GJets_Pt-100To200
  is_sim: true
  cross_section: 1024.0

- name: GJets_Pt-2000To5000
  is_sim: true
  cross_section: 7.476e-05

- name: GJets_Pt-200To500
  is_sim: true
  cross_section: 68.66

- name: GJets_Pt-20To100
  is_sim: true
  cross_section: 137800.0

- name: GJets_Pt-500To1000
  is_sim: true
  cross_section: 1.014

- name: GluGluHToZZTo2L2Nu_M800
  is_sim: true
  cross_section: 0.001346
  k_factor: ggF
  zz_2l2nu: true

- name: GluGluToContinToZZTo2e2nu
  is_sim: true
  cross_section: 0.01898
  k_factor: ggF
  zz_2l2nu: true

- name: GluGluToContinToZZTo2mu2nu
  is_sim: true
  cross_section: 0.01898
  k_factor: ggF
  zz_2l2nu: true

- name: GGToHToZZTo2E2Nu
  is_sim: true
  cross_section: 0.00586  # Generator cross section
  k_factor: ggF
  zz_2l2nu: true

- name: GGToHToZZTo2Mu2Nu
  is_sim: true
  cross_section: 0.00586  # Generator cross section
  k_factor: ggF
  zz_2l2nu: true

- name: GGToZZTo2E2Nu_BSI
  is_sim: true
  cross_section: 0.02149  # Generator cross section
  k_factor: ggF
  zz_2l2nu: true

- name: GGToZZTo2Mu2Nu_BSI
  is_sim: true
  cross_section: 0.02149  # Generator cross section
  k_factor: ggF
  zz_2l2nu: true

- name: QCD_HT1000to1500
  is_sim: true
  cross_section: 1207

- name: QCD_HT100to200
  is_sim: true
  cross_section: 27990000

- name: QCD_HT1500to2000
  is_sim: true
  cross_section: 119.9

- name: QCD_HT2000toInf
  is_sim: true
  cross_section: 25.24

- name: QCD_HT200to300
  is_sim: true
  cross_section: 1712000

- name: QCD_HT300to500
  is_sim: true
  cross_section: 347700

- name: QCD_HT500to700
  is_sim: true
  cross_section: 32100

- name: QCD_HT50to100
  is_sim: true
  cross_section: 246300000.0

- name: QCD_HT700to1000
  is_sim: true
  cross_section: 6831

- name: QCD_Pt-120to170_EMEnriched
  is_sim: true
  cross_section: 62964.0

- name: QCD_Pt-170to300_EMEnriched
  is_sim: true
  cross_section: 18810.0

- name: QCD_Pt-20to30_EMEnriched
  is_sim: true
  cross_section: 5352959.999999999

- name: QCD_Pt-20toInf_MuEnrichedPt15
  is_sim: true
  cross_section: 302672.16000000003

- name: QCD_Pt-300toInf_EMEnriched
  is_sim: true
  cross_section: 1350.0

- name: QCD_Pt-30to50_EMEnriched
  is_sim: true
  cross_section: 9928000.0

- name: QCD_Pt-50to80_EMEnriched
  is_sim: true
  cross_section: 2890800.0

- name: QCD_Pt-80to120_EMEnriched
  is_sim: true
  cross_section: 350000.0

- name: ST_s-channel
  is_sim: true
  cross_section: 3.362

- name: ST_t-channel_antitop
  is_sim: true
  cross_section: 70.69

- name: ST_t-channel_top
  is_sim: true
  cross_section: 70.69

- name: ST_tW_antitop
  is_sim: true
  cross_section: 35.6

- name: ST_tW_top
  is_sim: true
  cross_section: 35.6

- name: TGJets
  is_sim: true
  cross_section: 2.967

- name: TTGJets
  is_sim: true
  cross_section: 3.697

- name: TT
  is_sim: true
  cross_section: 831.76

- name: TTWJetsToLNu
  is_sim: true
  cross_section: 0.2043

- name: TTZToLLNuNu_M-10
  is_sim: true
  cross_section: 0.2529

- name: WGToLNuG
  is_sim: true
  cross_section: 489

- name: WJetsToLNu
  is_sim: true
  # NNLO cross section from FEWZ (https://twiki.cern.ch/twiki/bin/view/CMS/StandardModelCrossSectionsat13TeV?rev=26)
  cross_section: 61526.7

- name: WJetsToLNu_LO
  is_sim: true
  # NNLO cross section from FEWZ (https://twiki.cern.ch/twiki/bin/view/CMS/StandardModelCrossSectionsat13TeV?rev=26)
  cross_section: 61526.7
  me_kin_filter:  # Removes overlap with Ht-binned samples
    variable: Ht
    range: [0., 100.]

- name: WJetsToLNu_HT-100To200
  is_sim: true
  # Cross sections for this and other Ht-binned W+jets samples have been
  # computed by rescaling corresponding LO cross sections by the ratio between
  # NNLO and LO cross sections for the inclusive sample (which is around 1.21)
  cross_section: 1627.45

- name: WJetsToLNu_HT-200To400
  is_sim: true
  cross_section: 435.23699999999997

- name: WJetsToLNu_HT-400To600
  is_sim: true
  cross_section: 59.181099999999994

- name: WJetsToLNu_HT-600To800
  is_sim: true
  cross_section: 14.5805

- name: WJetsToLNu_HT-800To1200
  is_sim: true
  cross_section: 6.656210000000001

- name: WJetsToLNu_HT-1200To2500
  is_sim: true
  cross_section: 1.6080899999999998

- name: WJetsToLNu_HT-2500ToInf
  is_sim: true
  cross_section: 0.0389136

- name: WWTo2L2Nu
  is_sim: true
  cross_section: 12.178

- name: WWW
  is_sim: true
  cross_section: 0.2086  # https://twiki.cern.ch/twiki/bin/view/CMS/SummaryTable1G25ns?rev=152#Triboson

- name: WWZ
  is_sim: true
  cross_section: 0.1651

- name: WZTo2L2Q
  is_sim: true
  cross_section: 5.595

- name: WZTo3LNu
  is_sim: true
  cross_section: 4.42965
  ew_correction: WZ

- name: WZZ
  is_sim: true
  cross_section: 0.05565

- name: ZGTo2LG
  is_sim: true
  cross_section: 117.864

- name: ZGTo2NuG
  is_sim: true
  cross_section: 28.04

- name: ZGTo2NuG_PtG-130
  is_sim: true
  cross_section: 0.2768

- name: ZNuNuGJets_MonoPhoton_PtG-130
  is_sim: true
  cross_section: 0.223

- name: ZNuNuGJets_MonoPhoton_PtG-40to130
  is_sim: true
  cross_section: 2.816

- name: ZZTo2L2Nu
  is_sim: true
  cross_section: 0.564
  ew_correction: ZZ
  zz_2l2nu: true

- name: ZZTo2L2Q
  is_sim: true
  cross_section: 3.22

- name: ZZTo4L
  is_sim: true
  cross_section: 1.256

- name: ZZToTauTau2Nu
  is_sim: true
  cross_section: 0.564
  zz_2l2nu: true

- name: ZZToTauTau2Q
  is_sim: true
  cross_section: 3.22

- name: ZZZ
  is_sim: true
  cross_section: 0.01398

