- name: VBFToContinToZZTo2e2nu_Phantom
  is_sim: true
  cross_section: 0.001 

- name: VBFToContinToZZTo2l2nu
  is_sim: true
  cross_section: 0.001 

- name: VBFToContinToZZTo2mu2nu_Phantom
  is_sim: true
  cross_section: 0.001 

- name: VBFToHToZZTo2E2Nu_Phantom
  is_sim: true
  cross_section: 0.001 

- name: VBFToHToZZTo2Mu2Nu_Phantom
  is_sim: true
  cross_section: 0.001 

- name: VBFToZZTo2E2Nu_BSI_Phantom
  is_sim: true
  cross_section: 0.001 

- name: VBFToZZTo2Mu2Nu_BSI_Phantom
  is_sim: true
  cross_section: 0.001 

