# List of the systematic uncertainties that can be used in our framework, in
# correspondence with datasets that they affect. A dataset is affected by an
# uncertainty if at least one of the masks provided for that uncertainty is
# contained, as a substring, in the name of the dataset, as specified in its
# dataset definition file. A special mask "*" matches all simulated datasets.
#
# Please append this list and add a description when you add other uncertainties
# in the analysis.

# Uncertainty on electroweak corrections (comes from the virtual component)
ewk:
  processes: [ZZTo2L2Nu, WZTo3LNu]
  is_weight: true

# Uncertainty on PDF variation
pdf:
  processes: ["*"]
  is_weight: true

# Envelope uncertainty on QCD scale
QCDscale:
  processes: ["*"]
  is_weight: true

# Variation in renormalization scale in the matrix element
me_renorm:
  processes: ["*"]
  is_weight: true

# Variation in factorization scale
factor:
  processes: ["*"]
  is_weight: true

# Uncertainty on the value of alpha_S
alphaS:
  processes: ["*"]
  is_weight: true

# Uncertainty from btag scale factors
btag:
  processes: ["*"]
  is_weight: true

# Uncertainty from btag scale factors
bmistag:
  processes: ["*"]
  is_weight: true

# Uncertainty on the 3rd lepton veto
lepveto:
  processes: ["*"]
  is_weight: true

# Uncertainty in jet pt scale
jec:
  processes: ["*"]
  is_weight: false

# Uncertainty in jet pt resolution
jer:
  processes: ["*"]
  is_weight: false

# Variation in unclustered component in ptmiss
metuncl:
  processes: ["*"]
  is_weight: false

# Uncertainty in pileup cross section
pileup:
  processes: ["*"]
  is_weight: true

# Uncertainty in L1T prefiring weights
l1t_prefiring:
  processes: ["*"]
  is_weight: true

#Uncertainty in lepton efficiencies & scale factors
muonEff_syst:
  processes: ["*"]
  is_weight: true

muonEff_stat:
  processes: ["*"]
  is_weight: true

muonEff_pileup:
  processes: ["*"]
  is_weight: true

muonEff_altMC:
  processes: ["*"]
  is_weight: true

electronEff_syst:
  processes: ["*"]
  is_weight: true

electronEff_stat:
  processes: ["*"]
  is_weight: true
    
electronEff_pileup:
  processes: ["*"]
  is_weight: true

electronEff_altMC:
  processes: ["*"]
  is_weight: true
    
#Uncertainty in trigger efficiencies & scale factors
triggerEE:
  processes: ["*"]
  is_weight: true

triggerMuMu:
  processes: ["*"]
  is_weight: true

triggerEMu:
  processes: ["*"]
  is_weight: true
